### PR TITLE
Use a dedicated serializer

### PR DESCRIPTION
**Pull request by thewilkybarkid**
This abstracts normalization into dedicated (bi-directional) normalizers.

The only part I'm not happy with is that `BlogArticleNormalizer` requires `subjects` to contain (promised) subjects. This doesn't reflect the original JSON, as there it's only a list of IDs.

### CODE REVIEW

**Comment by thewilkybarkid** [comment]
`Subjects` can't be passed to `BlogArticleNormalizer`'s constructor as we end up with circular dependencies.

We could make it `SubjectAware`, or pass `Subjects` in the context. Both feel like a hack, but...

**Comment by thewilkybarkid** [comment]
Passing `snippet => true` in the normalization context should mean just a snippet is returned.

**Comment by thewilkybarkid** [comment]
I'm not sure of a way out of the circular dependency problem (Symfony would require a compiler pass to handle fulfilling `SubjectAware`), so I've add an `ApiSdk` class which handles setup for you. Feels a bit ugly.

**Comment by stephenwf** [comment]
Does Symfony have a max-depth option?

**Comment by thewilkybarkid** [comment]
No, do you think we need it? (We could use promises to mimic it, so new levels only are denormalized when requested.)

**Comment by thewilkybarkid** [comment]
Going to merge, might need some refactoring later.

**Pull request merged**
