### PR TITLE
Improve Proofreader usage

### PR DESCRIPTION
**Pull request by thewilkybarkid**

### CODE REVIEW

**Comment by thewilkybarkid** [comment]
Ping @giorgiosironi, not sure why it's failed

**Comment by giorgiosironi** [comment]
Newer versions are propagated daily, manually upgrading it on the `elife-libraries--ci`.

**Comment by giorgiosironi** [comment]
Now fails on tests?

**Comment by thewilkybarkid** [comment]
Thanks. Test failures are ok, being addressed in #84.

**Pull request merged**
