### PR TITLE
ELPP-2305 Update book reference editors

### PR DESCRIPTION
**Pull request by thewilkybarkid**

### CODE REVIEW

**Comment by thewilkybarkid** [comment]
Hmm, PHPCPD is right in that there's duplication here, but we're treating book references and book-chapter references as separate things, so it's a false positive.

**Comment by giorgiosironi** [comment]
The goal of the tool is that the more duplication there is, the more likely there is a correlation where changing one class will result in changing another (e.g. changing `authorsEtAl` or `editorsEtAl` from `bool` to another type; changing `Place` or `AuthorEntry` to a scalar like recently happened to the `journal` reference fields, or viceversa changing a scalar to an object). I think this calls for a trait containing private properties and getters (but not constructors), so that clients still see the classes as unrelated. They call them compiler-assisted copy&paste in fact.

**Comment by thewilkybarkid** [comment]
Yeah, I'm thinking an `@internal` trait is the way to go (on both the models and normalizers). They have the same essentially in the schema (https://github.com/elifesciences/api-raml/blob/develop/src/misc/reference.v1.yaml#L37).

**Comment by giorgiosironi** [comment]
Consistency between the data model and the classes is a good sign

**Review by giorgiosironi — APPROVED** [review]

**Pull request merged**
