### PR TITLE
Build definition

### PR DESCRIPTION
**Pull request by giorgiosironi**

### CODE REVIEW

**Comment by giorgiosironi** [comment]
The build with the lowest dependencies fails with:

```
1) test\eLife\ApiSdk\Client\BlogArticlesTest::it_gets_a_blog_article
17:09:46 JsonSchema\Exception\JsonDecodingException: The maximum stack depth has been exceeded
17:09:46 
17:09:46 /var/lib/jenkins-libraries-runner/workspace/pull-requests-libraries/api-sdk-php/PR-1/vendor/justinrainbow/json-schema/src/JsonSchema/RefResolver.php:106
17:09:46 /var/lib/jenkins-libraries-runner/workspace/pull-requests-libraries/api-sdk-php/PR-1/vendor/justinrainbow/json-schema/src/JsonSchema/RefResolver.php:181
17:09:46 /var/lib/jenkins-libraries-runner/workspace/pull-requests-libraries/api-sdk-php/PR-1/vendor/justinrainbow/json-schema/src/JsonSchema/RefResolver.php:141
17:09:46 /var/lib/jenkins-libraries-runner/workspace/pull-requests-libraries/api-sdk-php/PR-1/vendor/justinrainbow/json-schema/src/JsonSchema/RefResolver.php:162
17:09:46 /var/lib/jenkins-libraries-runner/workspace/pull-requests-libraries/api-sdk-php/PR-1/vendor/justinrainbow/json-schema/src/JsonSchema/RefResolver.php:136
17:09:46 /var/lib/jenkins-libraries-runner/workspace/pull-requests-libraries/api-sdk-php/PR-1/vendor/justinrainbow/json-schema/src/JsonSchema/RefResolver.php:162
17:09:46 /var/lib/jenkins-libraries-runner/workspace/pull-requests-libraries/api-sdk-php/PR-1/vendor/justinrainbow/json-schema/src/JsonSchema/RefResolver.php:136
17:09:46 /var/lib/jenkins-libraries-runner/workspace/pull-requests-libraries/api-sdk-php/PR-1/vendor/justinrainbow/json-schema/src/JsonSchema/RefResolver.php:162
17:09:46 /var/lib/jenkins-libraries-runner/workspace/pull-requests-libraries/api-sdk-php/PR-1/vendor/justinrainbow/json-schema/src/JsonSchema/RefResolver.php:136
17:09:46 /var/lib/jenkins-libraries-runner/workspace/pull-requests-libraries/api-sdk-php/PR-1/vendor/justinrainbow/json-schema/src/JsonSchema/RefResolver.php:162
17:09:46 /var/lib/jenkins-libraries-runner/workspace/pull-requests-libraries/api-sdk-php/PR-1/vendor/justinrainbow/json-schema/src/JsonSchema/RefResolver.php:136
17:09:46 /var/lib/jenkins-libraries-runner/workspace/pull-requests-libraries/api-sdk-php/PR-1/vendor/justinrainbow/json-schema/src/JsonSchema/RefResolver.php:199
17:09:46 /var/lib/jenkins-libraries-runner/workspace/pull-requests-libraries/api-sdk-php/PR-1/vendor/justinrainbow/json-schema/src/JsonSchema/RefResolver.php:129
17:09:46 /var/lib/jenkins-libraries-runner/workspace/pull-requests-libraries/api-sdk-php/PR-1/vendor/justinrainbow/json-schema/src/JsonSchema/RefResolver.php:181
17:09:46 /var/lib/jenkins-libraries-runner/workspace/pull-requests-libraries/api-sdk-php/PR-1/vendor/justinrainbow/json-schema/src/JsonSchema/RefResolver.php:141
17:09:46 /var/lib/jenkins-libraries-runner/workspace/pull-requests-libraries/api-sdk-php/PR-1/vendor/justinrainbow/json-schema/src/JsonSchema/RefResolver.php:162
17:09:46 /var/lib/jenkins-libraries-runner/workspace/pull-requests-libraries/api-sdk-php/PR-1/vendor/justinrainbow/json-schema/src/JsonSchema/RefResolver.php:136
17:09:46 /var/lib/jenkins-libraries-runner/workspace/pull-requests-libraries/api-sdk-php/PR-1/vendor/webmozart/json/src/JsonValidator.php:157
17:09:46 /var/lib/jenkins-libraries-runner/workspace/pull-requests-libraries/api-sdk-php/PR-1/vendor/webmozart/json/src/JsonValidator.php:74
17:09:46 /var/lib/jenkins-libraries-runner/workspace/pull-requests-libraries/api-sdk-php/PR-1/vendor/webmozart/json/src/JsonDecoder.php:112
17:09:46 /var/lib/jenkins-libraries-runner/workspace/pull-requests-libraries/api-sdk-php/PR-1/vendor/elife/api-validator/src/MessageValidator/JsonMessageValidator.php:51
17:09:46 /var/lib/jenkins-libraries-runner/workspace/pull-requests-libraries/api-sdk-php/PR-1/test/ValidatingStorageAdapter.php:29
17:09:46 /var/lib/jenkins-libraries-runner/workspace/pull-requests-libraries/api-sdk-php/PR-1/test/ApiTestCase.php:99
17:09:46 /var/lib/jenkins-libraries-runner/workspace/pull-requests-libraries/api-sdk-php/PR-1/test/Client/BlogArticlesTest.php:87
17:09:46 
```

**Comment by thewilkybarkid** [comment]
Fixed in d490b5daabe976d2ce0cf62e1a9c2cff94144c39.

**Comment by giorgiosironi** [comment]
Build is now green, so this can be merged to trigger the first run of https://ci--alfred.elifesciences.org/job/library-api-sdk-php/

**Comment by thewilkybarkid** [comment]
Does there need to be a `.gitkeep` in `build`?

**Comment by giorgiosironi** [comment]
Added `.gitkeep`, for some reason I had already an ignore `build/.keepme` locally.

**Pull request merged**
